try to force sql server not to start up

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -14,6 +14,21 @@ jobs:
       - name: Start db 
         run: |
           docker-compose up --build -d 
+      - name: Check db ready
+        run: |
+        for i in {1..2};
+        do 
+        docker exec test-db /opt/mssql-tools/bin/sqlcmd -S db -U sa -P Pass@word -q "SELECT 1;" &> /dev/null
+            if [ $? -eq 0 ]
+                then
+                echo "SQL Server ready"
+            else
+                echo "Not ready yet..."
+                sleep 1;
+            fi
+        done
+        echo "SQL server failed to start"
+        exit 1
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
